/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TechnicianIndexRouteImport } from './routes/technician/index'
import { Route as EmployeeIndexRouteImport } from './routes/employee/index'
import { Route as ContractorIndexRouteImport } from './routes/contractor/index'
import { Route as TechnicianStatusRouteImport } from './routes/technician/status'
import { Route as TechnicianLoginRouteImport } from './routes/technician/login'
import { Route as TechnicianHistoryRouteImport } from './routes/technician/history'
import { Route as EmployeeVendorsRouteImport } from './routes/employee/vendors'
import { Route as EmployeeReportsRouteImport } from './routes/employee/reports'
import { Route as EmployeePreventiveRouteImport } from './routes/employee/preventive'
import { Route as EmployeeOrdersRouteImport } from './routes/employee/orders'
import { Route as EmployeeMapRouteImport } from './routes/employee/map'
import { Route as EmployeeLoginRouteImport } from './routes/employee/login'
import { Route as EmployeeInventoryRouteImport } from './routes/employee/inventory'
import { Route as EmployeeCostsRouteImport } from './routes/employee/costs'
import { Route as EmployeeBuildingsRouteImport } from './routes/employee/buildings'
import { Route as ContractorLoginRouteImport } from './routes/contractor/login'
import { Route as ContractorInvoicesRouteImport } from './routes/contractor/invoices'
import { Route as ContractorHistoryRouteImport } from './routes/contractor/history'
import { Route as ContractorAssignedRouteImport } from './routes/contractor/assigned'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianIndexRoute = TechnicianIndexRouteImport.update({
  id: '/technician/',
  path: '/technician/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/contractor/',
  path: '/contractor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianStatusRoute = TechnicianStatusRouteImport.update({
  id: '/technician/status',
  path: '/technician/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianLoginRoute = TechnicianLoginRouteImport.update({
  id: '/technician/login',
  path: '/technician/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianHistoryRoute = TechnicianHistoryRouteImport.update({
  id: '/technician/history',
  path: '/technician/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeVendorsRoute = EmployeeVendorsRouteImport.update({
  id: '/employee/vendors',
  path: '/employee/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeReportsRoute = EmployeeReportsRouteImport.update({
  id: '/employee/reports',
  path: '/employee/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeePreventiveRoute = EmployeePreventiveRouteImport.update({
  id: '/employee/preventive',
  path: '/employee/preventive',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeOrdersRoute = EmployeeOrdersRouteImport.update({
  id: '/employee/orders',
  path: '/employee/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeMapRoute = EmployeeMapRouteImport.update({
  id: '/employee/map',
  path: '/employee/map',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLoginRoute = EmployeeLoginRouteImport.update({
  id: '/employee/login',
  path: '/employee/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeInventoryRoute = EmployeeInventoryRouteImport.update({
  id: '/employee/inventory',
  path: '/employee/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeCostsRoute = EmployeeCostsRouteImport.update({
  id: '/employee/costs',
  path: '/employee/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeBuildingsRoute = EmployeeBuildingsRouteImport.update({
  id: '/employee/buildings',
  path: '/employee/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorLoginRoute = ContractorLoginRouteImport.update({
  id: '/contractor/login',
  path: '/contractor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorInvoicesRoute = ContractorInvoicesRouteImport.update({
  id: '/contractor/invoices',
  path: '/contractor/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorHistoryRoute = ContractorHistoryRouteImport.update({
  id: '/contractor/history',
  path: '/contractor/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorAssignedRoute = ContractorAssignedRouteImport.update({
  id: '/contractor/assigned',
  path: '/contractor/assigned',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/contractor/assigned': typeof ContractorAssignedRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/invoices': typeof ContractorInvoicesRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/employee/buildings': typeof EmployeeBuildingsRoute
  '/employee/costs': typeof EmployeeCostsRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/map': typeof EmployeeMapRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/preventive': typeof EmployeePreventiveRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/vendors': typeof EmployeeVendorsRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/status': typeof TechnicianStatusRoute
  '/contractor/': typeof ContractorIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/technician/': typeof TechnicianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/contractor/assigned': typeof ContractorAssignedRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/invoices': typeof ContractorInvoicesRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/employee/buildings': typeof EmployeeBuildingsRoute
  '/employee/costs': typeof EmployeeCostsRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/map': typeof EmployeeMapRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/preventive': typeof EmployeePreventiveRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/vendors': typeof EmployeeVendorsRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/status': typeof TechnicianStatusRoute
  '/contractor': typeof ContractorIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/technician': typeof TechnicianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request': typeof RequestRoute
  '/contractor/assigned': typeof ContractorAssignedRoute
  '/contractor/history': typeof ContractorHistoryRoute
  '/contractor/invoices': typeof ContractorInvoicesRoute
  '/contractor/login': typeof ContractorLoginRoute
  '/employee/buildings': typeof EmployeeBuildingsRoute
  '/employee/costs': typeof EmployeeCostsRoute
  '/employee/inventory': typeof EmployeeInventoryRoute
  '/employee/login': typeof EmployeeLoginRoute
  '/employee/map': typeof EmployeeMapRoute
  '/employee/orders': typeof EmployeeOrdersRoute
  '/employee/preventive': typeof EmployeePreventiveRoute
  '/employee/reports': typeof EmployeeReportsRoute
  '/employee/vendors': typeof EmployeeVendorsRoute
  '/technician/history': typeof TechnicianHistoryRoute
  '/technician/login': typeof TechnicianLoginRoute
  '/technician/status': typeof TechnicianStatusRoute
  '/contractor/': typeof ContractorIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/technician/': typeof TechnicianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request'
    | '/contractor/assigned'
    | '/contractor/history'
    | '/contractor/invoices'
    | '/contractor/login'
    | '/employee/buildings'
    | '/employee/costs'
    | '/employee/inventory'
    | '/employee/login'
    | '/employee/map'
    | '/employee/orders'
    | '/employee/preventive'
    | '/employee/reports'
    | '/employee/vendors'
    | '/technician/history'
    | '/technician/login'
    | '/technician/status'
    | '/contractor/'
    | '/employee/'
    | '/technician/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request'
    | '/contractor/assigned'
    | '/contractor/history'
    | '/contractor/invoices'
    | '/contractor/login'
    | '/employee/buildings'
    | '/employee/costs'
    | '/employee/inventory'
    | '/employee/login'
    | '/employee/map'
    | '/employee/orders'
    | '/employee/preventive'
    | '/employee/reports'
    | '/employee/vendors'
    | '/technician/history'
    | '/technician/login'
    | '/technician/status'
    | '/contractor'
    | '/employee'
    | '/technician'
  id:
    | '__root__'
    | '/'
    | '/request'
    | '/contractor/assigned'
    | '/contractor/history'
    | '/contractor/invoices'
    | '/contractor/login'
    | '/employee/buildings'
    | '/employee/costs'
    | '/employee/inventory'
    | '/employee/login'
    | '/employee/map'
    | '/employee/orders'
    | '/employee/preventive'
    | '/employee/reports'
    | '/employee/vendors'
    | '/technician/history'
    | '/technician/login'
    | '/technician/status'
    | '/contractor/'
    | '/employee/'
    | '/technician/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestRoute: typeof RequestRoute
  ContractorAssignedRoute: typeof ContractorAssignedRoute
  ContractorHistoryRoute: typeof ContractorHistoryRoute
  ContractorInvoicesRoute: typeof ContractorInvoicesRoute
  ContractorLoginRoute: typeof ContractorLoginRoute
  EmployeeBuildingsRoute: typeof EmployeeBuildingsRoute
  EmployeeCostsRoute: typeof EmployeeCostsRoute
  EmployeeInventoryRoute: typeof EmployeeInventoryRoute
  EmployeeLoginRoute: typeof EmployeeLoginRoute
  EmployeeMapRoute: typeof EmployeeMapRoute
  EmployeeOrdersRoute: typeof EmployeeOrdersRoute
  EmployeePreventiveRoute: typeof EmployeePreventiveRoute
  EmployeeReportsRoute: typeof EmployeeReportsRoute
  EmployeeVendorsRoute: typeof EmployeeVendorsRoute
  TechnicianHistoryRoute: typeof TechnicianHistoryRoute
  TechnicianLoginRoute: typeof TechnicianLoginRoute
  TechnicianStatusRoute: typeof TechnicianStatusRoute
  ContractorIndexRoute: typeof ContractorIndexRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  TechnicianIndexRoute: typeof TechnicianIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/': {
      id: '/technician/'
      path: '/technician'
      fullPath: '/technician/'
      preLoaderRoute: typeof TechnicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/': {
      id: '/employee/'
      path: '/employee'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/contractor'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/status': {
      id: '/technician/status'
      path: '/technician/status'
      fullPath: '/technician/status'
      preLoaderRoute: typeof TechnicianStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/login': {
      id: '/technician/login'
      path: '/technician/login'
      fullPath: '/technician/login'
      preLoaderRoute: typeof TechnicianLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/history': {
      id: '/technician/history'
      path: '/technician/history'
      fullPath: '/technician/history'
      preLoaderRoute: typeof TechnicianHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/vendors': {
      id: '/employee/vendors'
      path: '/employee/vendors'
      fullPath: '/employee/vendors'
      preLoaderRoute: typeof EmployeeVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/reports': {
      id: '/employee/reports'
      path: '/employee/reports'
      fullPath: '/employee/reports'
      preLoaderRoute: typeof EmployeeReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/preventive': {
      id: '/employee/preventive'
      path: '/employee/preventive'
      fullPath: '/employee/preventive'
      preLoaderRoute: typeof EmployeePreventiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/orders': {
      id: '/employee/orders'
      path: '/employee/orders'
      fullPath: '/employee/orders'
      preLoaderRoute: typeof EmployeeOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/map': {
      id: '/employee/map'
      path: '/employee/map'
      fullPath: '/employee/map'
      preLoaderRoute: typeof EmployeeMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/login': {
      id: '/employee/login'
      path: '/employee/login'
      fullPath: '/employee/login'
      preLoaderRoute: typeof EmployeeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/inventory': {
      id: '/employee/inventory'
      path: '/employee/inventory'
      fullPath: '/employee/inventory'
      preLoaderRoute: typeof EmployeeInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/costs': {
      id: '/employee/costs'
      path: '/employee/costs'
      fullPath: '/employee/costs'
      preLoaderRoute: typeof EmployeeCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/buildings': {
      id: '/employee/buildings'
      path: '/employee/buildings'
      fullPath: '/employee/buildings'
      preLoaderRoute: typeof EmployeeBuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/login': {
      id: '/contractor/login'
      path: '/contractor/login'
      fullPath: '/contractor/login'
      preLoaderRoute: typeof ContractorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/invoices': {
      id: '/contractor/invoices'
      path: '/contractor/invoices'
      fullPath: '/contractor/invoices'
      preLoaderRoute: typeof ContractorInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/history': {
      id: '/contractor/history'
      path: '/contractor/history'
      fullPath: '/contractor/history'
      preLoaderRoute: typeof ContractorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/assigned': {
      id: '/contractor/assigned'
      path: '/contractor/assigned'
      fullPath: '/contractor/assigned'
      preLoaderRoute: typeof ContractorAssignedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestRoute: RequestRoute,
  ContractorAssignedRoute: ContractorAssignedRoute,
  ContractorHistoryRoute: ContractorHistoryRoute,
  ContractorInvoicesRoute: ContractorInvoicesRoute,
  ContractorLoginRoute: ContractorLoginRoute,
  EmployeeBuildingsRoute: EmployeeBuildingsRoute,
  EmployeeCostsRoute: EmployeeCostsRoute,
  EmployeeInventoryRoute: EmployeeInventoryRoute,
  EmployeeLoginRoute: EmployeeLoginRoute,
  EmployeeMapRoute: EmployeeMapRoute,
  EmployeeOrdersRoute: EmployeeOrdersRoute,
  EmployeePreventiveRoute: EmployeePreventiveRoute,
  EmployeeReportsRoute: EmployeeReportsRoute,
  EmployeeVendorsRoute: EmployeeVendorsRoute,
  TechnicianHistoryRoute: TechnicianHistoryRoute,
  TechnicianLoginRoute: TechnicianLoginRoute,
  TechnicianStatusRoute: TechnicianStatusRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  TechnicianIndexRoute: TechnicianIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
